yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Wikelo missions
site_url: https://jeffta.github.io/wikelo-missions/
repo_url: https://github.com/jeffta/wikelo-missions
repo_name: jeffta/wikelo-missions

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Clear mode

plugins:
  - search

nav:
  - Home: index.md